Add missing syncs for G_PM_NPRIMITIVE
HackerN64/HackerSM64 pull request #345
Opened 2022-03-11 16:15 UTC by FazanaJ

Allows G_PM_NPRIMITIVE to function fully without crashing or visual artefacting, providing minor speedup on the RDP.

2022-03-18 17:40 UTC, thecozies approved these changes
lgtm

2022-03-18 17:44 UTC, thecozies requested changes
make some tweaks or something

2022-03-18 17:50 UTC, FazanaJ commented
I have reviewed my own code and have found myself to have done no wrongdoing

2022-03-18 17:54 UTC, thecozies approved these changes
pretty suspicious, still looks good

2022-03-18 17:59 UTC, Mr-Wiseguy requested changes

2022-03-18 17:59 UTC, Mr-Wiseguy commented on actors/sparkle_animation/model.inc.c
> +    gsDPPipeSync(),
Move this one line down

2022-03-18 17:59 UTC, Mr-Wiseguy commented on bin/debug_level_select.c
> +    gsDPPipeSync(),
Not needed

2022-03-18 17:59 UTC, Mr-Wiseguy commented on bin/debug_level_select.c
> +    gsDPPipeSync(),
Not needed

2022-03-18 17:59 UTC, Mr-Wiseguy commented on bin/debug_level_select.c
> +    gsDPPipeSync(),
Not needed

2022-03-18 17:59 UTC, Mr-Wiseguy commented on bin/debug_level_select.c
> +    gsDPPipeSync(),
Not needed

2022-03-25 17:00 UTC, Mr-Wiseguy requested changes

2022-03-25 17:00 UTC, Mr-Wiseguy commented on bin/segment2.c
> +    gsDPPipeSync(),
Still here

2022-03-25 17:00 UTC, Mr-Wiseguy commented on actors/sparkle_animation/model.inc.c
> +    gsDPPipeSync(),
Move

2022-03-25 17:07 UTC, Mr-Wiseguy approved these changes
looketh good to me

2022-03-25 17:08 UTC, merged