Puppycamera hotfixes
HackerN64/HackerSM64 pull request #367
Opened 2022-03-25 11:24 UTC by FazanaJ

Volumes should build correctly now.

2022-03-25 11:26 UTC, arthurtilly commented
making fun of fazana thread lets go!

2022-03-25 11:27 UTC, Reonu commented
puppycam more like poopycam!!!!! lol!!!!!!!!!!!!

2022-03-27 01:57 UTC, Mr-Wiseguy requested changes

2022-03-27 01:57 UTC, Mr-Wiseguy commented on README.md
> -- Lighting Engine is available on a separate branch ([base/lighting-engine-wip](https://github.com/Reonu/HackerSM64/tree/base/lighting-engine-wip)). Instructions on how to use it are in the readme of
This change was pulled in when I changed the target branch to develop/2.0.1, go ahead and delete it from the PR and it'll be good to merge

2022-03-27 07:20 UTC, Mr-Wiseguy approved these changes

2022-03-27 07:20 UTC, merged