Update math_util.c
HackerN64/HackerSM64 pull request #410
Opened 2022-05-31 22:48 UTC by KazeEmanuar

yipped backface culling

2022-05-31 22:48 UTC, KazeEmanuar commented
yip it to the net!

2022-05-31 22:51 UTC, thecozies requested changes
close!

2022-05-31 22:51 UTC, thecozies commented on src/engine/math_util.c
>      // Check if we're perpendicular from the surface.
```suggestion
    // Check if we're perpendicular or pointing away from the surface.
```

2022-05-31 22:51 UTC, thecozies commented on src/engine/math_util.c
> +    if ((det < NEAR_ZERO)) return FALSE;
too many parenthesis
```suggestion
    if (det < NEAR_ZERO) return FALSE;
```

2022-06-09 00:09 UTC, Reonu approved these changes
gogogo

2022-06-09 00:09 UTC, NyakoFox commented
yip

2022-06-09 00:10 UTC, thecozies approved these changes
yip

2022-06-09 00:31 UTC, KazeEmanuar commented
SHUT UP

Am Mi., 8. Juni 2022 um 21:10 Uhr schrieb thecozies <
***@***.***>:

> ***@***.**** approved this pull request.
>
> yip
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackerN64/HackerSM64/pull/410#pullrequestreview-1000581954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBZDY4DOLM2IBZLSTVL5OLVOEY6TANCNFSM5XPBTTLQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-09 00:55 UTC, axollyon commented
hi kayze

2022-06-09 01:12 UTC, Reonu commented
yo kaze I like your inbox

2022-06-09 14:04 UTC, Mr-Wiseguy approved these changes

2022-06-09 14:04 UTC, merged