Replace unused 0C bank with aglab's / scut's extended 0C bank
HackerN64/HackerSM64 pull request #412
Opened 2022-06-01 02:26 UTC by Reonu

This is used by a lot of music ports and it's overall a good feature for the repo to have.

The bank it's replacing is unused and useless. Any usecase that it might have is also covered by this bank.

2022-06-01 02:37 UTC, gheskett requested changes

2022-06-01 02:37 UTC, gheskett commented on sound/sound_banks/0C_extended_bank.json
> +		"Crash Cymbal",
These use two tabs, while everything else uses 8 spaces.

2022-06-01 02:40 UTC, gheskett commented
Before approving, I will also look at the audio memory pools and make sure everything looks good. I'm currently out of town but I'll look at it when I have the opportunity.

2022-06-03 00:11 UTC, gheskett approved these changes
Extended bank should work fine in most use cases, based on what I've tested.

2022-07-19 04:36 UTC, arthurtilly commented
looks good

2022-07-22 13:59 UTC, thecozies approved these changes

2022-07-22 14:00 UTC, merged