New Crash Screen
HackerN64/HackerSM64 pull request #466
Opened 2022-07-25 00:49 UTC by gheskett

_TODO: In-depth description still needed._

2022-08-03 21:07 UTC, someone2639 requested changes

2022-08-03 21:07 UTC, someone2639 commented on include/sm64.h
> +#define ASSERT(cond, message) do {\
imo if this is a runtime assert that follows the C standard then it should be named `assert` in all lowercase

2022-08-03 21:07 UTC, someone2639 commented on src/crash_screen/crash_screen.c
> +    "AT", "V0", "V1",
what happened to `r0` lol (also theres 32 general registers where did the other 2 besides `r0` go)

2022-08-03 21:07 UTC, someone2639 commented on src/crash_screen/insn_disasm.h
> +    PARAM_STD, // rs, rd, rt
SDT?

2022-08-03 21:07 UTC, someone2639 commented on src/crash_screen/map_parser.c
> +s32 is_in_code_segment(uintptr_t addr) {
if `boot` segment doesnt get overwritten it should be added here

2022-08-03 21:07 UTC, someone2639 commented on src/crash_screen/map_parser.h
> +    /*0x04*/ size_t name_offset;
should be uintptr_t since its an offset

2022-08-03 21:07 UTC, someone2639 commented on src/crash_screen/map_parser.h
> +#define ADDR_IS_KNOWN(addr) ((*(uintptr_t*)(addr) & 0x80000000) != 0)
this could probably be merged into `IS_IN_SEGMENT` with no issues

2022-08-03 21:07 UTC, someone2639 commented on include/sm64.h
> +#define ASSERT(cond, message) do {\
on second thought that requires a bit of extra work (including meddling with n64_assert.s and the assert parser) so consider this comment optional

2023-10-06 13:35 UTC, someone2639 commented
Something I would like to see on this branch is a list of things this PR will do, so that scope is limited to only those things and I can gauge what parts I can contribute to (I'm willing to write the list but I do want mutual agreement here).

2023-10-06 20:32 UTC, closed without merging

2023-10-06 20:32 UTC, Arceveti commented
Moving to new PR