Make objects not run their code if the room they are in isn't loaded.
HackerN64/HackerSM64 pull request #502
Opened 2022-09-29 22:18 UTC by arthurtilly

* Object flag for forcing objects to always be loaded regardless of room
* Does nothing if the object doesn't call bhv_init_room

2022-09-30 03:39 UTC, gheskett commented
Potentially replaces #416

2022-09-30 05:43 UTC, gheskett requested changes

2022-09-30 05:43 UTC, gheskett commented on src/game/object_helpers.c
> +u32 is_room_loaded(s32 room) {
Unused parameter

2022-09-30 05:51 UTC, gheskett commented on src/engine/behavior_script.c
> +            cur_obj_enable_rendering_if_mario_in_room();
Slight nitpick, but it probably makes more sense to copy the three lines out of the `else` block in this function to skip the three unnecessary conditions.

2022-09-30 06:22 UTC, gheskett approved these changes
I assume this has been properly tested to work in-game, and if so then LGTM

2022-11-01 23:59 UTC, Reonu approved these changes
looks good to me i fucked your mom etc

2022-11-02 21:18 UTC, Reonu approved these changes
I like this PR so much I'm approving it again

2022-11-02 22:35 UTC, arthurtilly commented
fuck cozies i am based

2022-11-02 22:35 UTC, merged