2.0.8
HackerN64/HackerSM64 pull request #543
Opened 2022-12-05 15:47 UTC by someone2639

the j

2022-12-05 15:54 UTC, thecozies requested changes

2022-12-05 15:54 UTC, thecozies commented on VERSION.txt
> +v2.0.9
the

2022-12-05 15:55 UTC, gheskett commented on VERSION.txt
> +v2.0.9
True!

2022-12-05 16:24 UTC, gheskett commented
> i'm going to commit sudoku

|   | 3 | 1 | 4 |   |   |   |   |   |
| - | - | - | - | - | - | - | - | - |
|   |   | 8 |   |   |   |   | 3 |   |
|   |   |   |   |   | 8 | 9 |   | 7 |
| 4 | 9 |   | 1 |   |   | 8 |   | 5 |
|   |   | 6 | 5 |   | 9 |   | 7 |   |
|   |   |   |   |   |   | 1 |   |   |
| 3 |   | 4 |   | 1 | 7 |   | 9 |   |
|   | 6 |   |   | 9 |   | 5 |   |   |
| 8 |   |   | 2 |   |   |   |   |   |

2022-12-05 16:26 UTC, gheskett approved these changes
F

2022-12-05 19:08 UTC, axollyon approved these changes
should've been 2.0.∞

2022-12-05 19:08 UTC, axollyon commented
wait why tf is your repo still called ultrasm64-extbounds

2022-12-05 19:11 UTC, gheskett commented
> ![image](https://user-images.githubusercontent.com/9752483/205719826-85246dab-cf7f-49c6-be66-34d68bd90c7f.png)

First 3x3 box has two 1's; try again

2022-12-06 15:18 UTC, thecozies approved these changes

2022-12-06 17:45 UTC, Reonu commented
sooooo are we merging this

2022-12-06 20:41 UTC, merged