Small improvements to object loading within rooms
HackerN64/HackerSM64 pull request #580
Opened 2023-02-18 04:14 UTC by axollyon

* Only check if Mario is in the same room as the object once
  * Since #502, objects without the `OBJ_FLAG_PROCESS_OUTSIDE_ROOM` flag were checking if they were in the same room as Mario twice. This eliminates that by splitting the `cur_obj_enable_rendering_if_mario_in_room` function into two separate functions: `is_mario_in_room`, and `cur_obj_enable_disable_room_rendering`. 
* Implement object render distance within rooms (from @thecozies)
  * Specifically from this Dog Collab commit: https://github.com/Cheezepin/dog_collab/commit/2eb05ca8c579df4f8d893819adaa42b872f26200

2023-02-18 06:16 UTC, gheskett requested changes
Funny sleepy brain mobile review (will re-review more thoroughly later when I can actually follow what was changed).

2023-02-18 06:16 UTC, gheskett commented on src/game/object_helpers.c
> +    return -1;
Boolean moment (enums please!)

2023-03-07 00:21 UTC, thecozies approved these changes

2023-03-07 01:49 UTC, gheskett approved these changes

2023-03-07 01:49 UTC, merged