Culling improvements + GRAPH_RENDER_INVISIBLE check change
HackerN64/HackerSM64 pull request #590
Opened 2023-03-07 19:59 UTC by Lilaa3

GRAPH_RENDER_INVISIBLE is now checked before computing any transformation matrix for the object. Half fov for vertical and horizontal culling is now computed during geo_process_perspective. Vertical culling has been added.
Emulators have basically infinite culling aspect ratio to prevent early culling with widescreen viewport hacks. This was written by both me and Kaze Emanuar, he provided the suggestion to use absolute values to reduce conditions.

2023-03-08 05:55 UTC, gheskett commented on src/engine/graph_node.h
> +    /*0x26*/ u16 near;  // near clipping plane
This offset is not correct. Also is there actually any reason for us to leave the `unused` field in this struct?

2023-03-08 05:57 UTC, gheskett commented on src/game/rendering_graph_node.c
>   * or horizontally out of view. It does not check whether it is vertically
Description contradicts itself

2023-06-21 23:47 UTC, gheskett requested changes

2023-06-21 23:47 UTC, gheskett commented on include/config/config_graphics.h
> +#define DEFAULT_CULLING_RADIUS 300
Nitpick, but please add the newline here lmao

2023-06-22 18:14 UTC, gheskett approved these changes
Additional review needed before merging

2023-06-23 14:03 UTC, thecozies approved these changes
super minor changes but i tested functionality and it works really well!! this is a nice and cleanly written optimization

approving but please add those suggestions i dropped here, then we can merrrrgggggeeeee

2023-06-23 14:03 UTC, thecozies commented on src/game/rendering_graph_node.c
> +
some extra whitespace is here

```suggestion

```

2023-06-23 15:06 UTC, merged