Rotate envmaps to be consistent with vanilla
HackerN64/HackerSM64 pull request #636
Opened 2023-06-12 18:27 UTC by gheskett

The script has been modified to support CCW envmap rotation; the in-game DLs still need updated before this can be opened fully.

2023-09-03 01:08 UTC, thecozies requested changes

2023-09-03 01:08 UTC, thecozies commented on actors/mario/model.inc.c
> +    gsSPTexture(0x07C0, 0x0F80, 0, G_TX_RENDERTILE, G_ON),
ill fix it

2023-09-03 01:09 UTC, Mineqwerty commented on actors/mario/model.inc.c
> +    gsSPTexture(0x07C0, 0x0F80, 0, G_TX_RENDERTILE, G_ON),
petervoid

2023-09-03 01:14 UTC, thecozies approved these changes

2023-09-03 01:32 UTC, thecozies requested changes
need:
```
inside_castle_seg7_texture_light_radial_inverse - levels/castle_inside/16.ia16.inc.c
cotmc_seg7_texture_07001800 - levels/cotmc/2.rgba16.inc.c

gd_texture_red_star_0
gd_texture_red_star_1
gd_texture_red_star_2
gd_texture_red_star_3
gd_texture_red_star_4
gd_texture_red_star_5
gd_texture_red_star_6
gd_texture_red_star_7
gd_texture_white_star_0
gd_texture_white_star_1
gd_texture_white_star_2
gd_texture_white_star_3
gd_texture_white_star_4
gd_texture_white_star_5
gd_texture_white_star_6
gd_texture_white_star_7
gd_texture_sparkle_0
gd_texture_sparkle_1
gd_texture_sparkle_2
gd_texture_sparkle_3
gd_texture_sparkle_4
gd_texture_mario_face_shine

paintings:
inside_castle_seg7_texture_07017000 ddd
inside_castle_seg7_texture_07016800 hmc
hmc_seg7_texture_07024CE0 levels/hmc/areas/1/painting.inc.c

```

2023-09-07 02:21 UTC, Mineqwerty commented
the painting textures are actually already in here
![image](https://github.com/HackerN64/HackerSM64/assets/29109093/1f6efad2-f1ea-4433-9915-3fa22b3775bf)

2023-09-17 16:13 UTC, gheskett reviewed
Approved kinda sorta I think (I cannot review my own PRs) (also I am just kinda assuming everything I didn't do is good here)

2023-09-18 13:10 UTC, merged