Improved WiiVC check to avoid false positives & added functions to read and manipulate fcr31
HackerN64/HackerSM64 pull request #669
Opened 2023-09-01 21:16 UTC by mpharoah

Added functions to manage the current floating point rounding mode and exceptions. Also improved the WiiVC check so that hacks using alternate rounding modes don't get incorrectly detected as WiiVC.

Tested on console and all relevant PC emulators, but I'll need someone to test on an actual Wii to verify that the check still works as expected.

2023-09-16 06:18 UTC, gheskett approved these changes

2023-09-18 02:41 UTC, someone2639 commented on asm/fcr31.s
> +andi $v0, 0x3
Only comment I have here is that these masks and flags have pretty names in PR/R4300.h with _LANGUAGE_ASSEMBLY defined (e.g. this 0x3 is `FPCSR_RM_MASK`)

2023-09-18 02:46 UTC, someone2639 commented on asm/fcr31.s
> +andi $v0, 0x3
actually this might be the only one thats easy to drop in lol

2023-09-18 02:52 UTC, someone2639 approved these changes
no reason to request changes over one sdk name so yeah

2023-09-22 04:08 UTC, gheskett requested changes
Could we move `float.h` into the include folder or somewhere that's not the game folder?

2023-09-22 12:46 UTC, mpharoah commented
Done

2023-09-22 13:36 UTC, thecozies approved these changes

2023-09-22 17:05 UTC, gheskett approved these changes

2023-09-22 17:05 UTC, merged