Remove OBJECTS_REJ and clean up core render func
HackerN64/HackerSM64 pull request #717
Opened 2023-09-30 19:01 UTC by FazanaJ

Completely purged it. I've made a few changes to the function for the sake of cleanliness, but also efficiency, and I fixed the crash caused by debug boxes.

2023-10-04 08:57 UTC, someone2639 reviewed
Since this is 2.2 according to the board the only changes necessary would be to merge the latest changes then its ready to go

2023-10-04 08:57 UTC, someone2639 commented on VERSION.txt
> +v2.1.2
version meme

2023-10-12 16:07 UTC, gheskett requested changes
This entire branch appears to be based off 2.1.2. This branch needs to be restarted/rebased to be founded off of `develop/2.2.0` in order to be considered for merge.

2023-10-12 16:07 UTC, gheskett commented on src/game/rendering_graph_node.c
>      // No silhouette, no .rej
.rej comment

2023-10-12 16:07 UTC, gheskett commented on src/game/rendering_graph_node.c
>      // Silhouette, no .rej
.rej comment

2023-10-12 16:07 UTC, gheskett commented on src/game/rendering_graph_node.c
> +        render_debug_boxes(&gfx);
What happened to `hitboxView`?

2023-10-12 16:07 UTC, gheskett commented on src/game/rendering_graph_node.h
>      // No silhouette, no .rej
.rej comment

2023-12-15 04:29 UTC, gheskett commented
@FazanaJ please update this thanks

2023-12-15 06:12 UTC, closed without merging

2023-12-15 06:14 UTC, gheskett commented
Moved to #735