Add assert for beginning geo layout command
HackerN64/HackerSM64 pull request #738
Opened 2023-12-17 05:59 UTC by arthurtilly

Fixes #570. Checks if the beginning command of the geo layout is a valid command to start, to make it easier to tell when an invalid model is trying to load.

The check is kinda hardcoded, but doing it with just a range check for a valid geo layout command makes the assert have too many false negatives to be useful.

2023-12-17 06:13 UTC, gheskett approved these changes

2024-01-20 18:16 UTC, gheskett requested changes
Now that I've actually spent nonzero time with these, this seems probably not correct. If the idea is to just make sure the command is valid, why not check for something entirely out of enum range instead? Might leave this to be more vulnerable, but you also don't want to potentially block fast64 with a false-positive just because it maybe doesn't exist in vanilla.

2024-01-20 18:19 UTC, arthurtilly commented
this was actually the first thing i tried, but its pretty much completely useless. making the check just the enum range makes the check pretty much never trigger even when you do load an invalid geo layout / model, in fact i wasnt able to get it to successfully trigger even once. the hardcoded check is definitely ugly but at least ive tested and it makes the assert actually function in the cases you want it to

2024-01-20 18:21 UTC, arthurtilly commented
also i literally said this reason in the PR description itself smh did u not read it

2024-01-20 18:22 UTC, gheskett commented
My concern here is it's seemingly missing cases. What about `GEO_CMD_NODE_ROTATION` and `GEO_CMD_NODE_TRANSLATION_ROTATION`? Do you know for sure all of the other ones that exist definitely don't work?

2024-01-20 18:24 UTC, arthurtilly commented
nope you should probably check with some other people for that. but at the very least i don't think vanilla models nor fast64 exports ever start with those commands (not totally convinced about the fast64 exports but i think theyd be more predictable). i feel like as long as those bases are covered then its likely safe enough. maybe ask lila about it

2024-01-20 20:39 UTC, gheskett commented
TODO: Report model ID inside assertion (if possible). Might not be able to use a stack-allocated string for this?

2024-01-21 18:34 UTC, gheskett approved these changes

2024-01-21 18:37 UTC, arthurtilly commented
comment

2024-01-21 18:38 UTC, merged