Label unlabelled audio func (func_80321080 to play_primary_music)
HackerN64/HackerSM64 pull request #782
Opened 2024-04-14 15:27 UTC by Reonu

I've used this function a bunch in my hacks and it's weird that it isn't labelled. It isn't some obscure function you'd never want to use, it's just to cancel the secondary music (like the piranha plant lullaby) and go back to playing the level's music.

2024-04-14 15:39 UTC, gheskett requested changes
Seems like it would be more accurate to call this something like `stop_secondary_music()`

2024-04-14 16:19 UTC, Reonu commented
> Seems like it would be more accurate to call this something like `stop_secondary_music()`

Sure

2024-04-14 19:38 UTC, arthurtilly approved these changes

2024-04-15 00:52 UTC, gheskett approved these changes

2024-04-15 00:59 UTC, merged